### ISSUE TITLE
Add Example Component Picker

### ISSUE THREAD

**Issue by daviddossantos** [unform/unform#286]
**What would you like to be added**:
Component Picker - React Native
I had to add the picker component to a project I was developing, I was already using unform and I didn't have any examples of implementation with it.

**Why is this needed**:
I believe that just like me, someone needed to use a picker along with the unform form and did not know how to implement. When searching the internet i didn't find related examples. I found a solution and would like to share it with the community :)

To reach this solution, I used the lib [**react-native-picker-select**](https://github.com/lawnstarter/react-native-picker-select), works on android and ios.

**Is your enhancement request related to a problem? Please describe.**
No

**Additional context**
Used picke along unform:
[**View Example on snack.expo.io**](https://snack.expo.io/@git/github.com/daviddossantos/picker-unform)

| Android Example 	| Android Example 	|
|-------------	|-------------	|
| ![android-example-01](https://user-images.githubusercontent.com/37313667/88811686-3f406480-d18d-11ea-84d5-24fbe99758b6.png) | ![android-example-02](https://user-images.githubusercontent.com/37313667/88811679-3ea7ce00-d18d-11ea-808e-e0073e8fa70c.png) | 

| iOS Example 	| iOS Example 	|
|-------------	|-------------	|
| ![ios-example-01](https://user-images.githubusercontent.com/37313667/88811967-97776680-d18d-11ea-91c3-bbc27427c877.png)  | ![ios-example-02](https://user-images.githubusercontent.com/37313667/88811972-98a89380-d18d-11ea-9efe-84b69e618456.png) |

**Comment by daviddossantos** [comment]
thanks @EliasGcf

**Comment by Jonathansoufer** [comment]
Good job man, I was looking for it. Although I'll try to use @react-native-community/picker, your code will help me get there.

**Comment by daviddossantos** [comment]
Thanks @Jonathansoufer, any questions so comment here 😁

**Comment by luanccp** [comment]
> Good job man, I was looking for it. Although I'll try to use @react-native-community/picker, your code will help me get there.

Hey @Jonathansoufer how did you integrate with the @react-native-community/picker?
I'm trying for hours but I cannot get there

**Comment by dededavida** [comment]
@luanccp, the implementation I made is not for your case?

**Comment by luanccp** [comment]
> @luanccp, the implementation I made is not for your case?

Unfortunately, I have to use @react-native-community/picker. And I can't integrate the unform/mobile with my picker. I'm not getting the value :/

**Comment by dededavida** [comment]
precisely for that reason use another picker library, because you cannot get the picker value

**Comment by Jonathansoufer** [comment]
I integrated with react-native-picker-select

**Comment by Jonathansoufer** [comment]
I created a component (see below)

```
import { useField } from "@unform/core";
import React, {
  useEffect,
  useState,
  useRef,
  forwardRef,
} from 'react';
import styled, { css } from 'styled-components/native';
import { StyleSheet, Dimensions, Platform } from "react-native";
import RNPickerSelect from "react-native-picker-select";
import MCIcon from 'react-native-vector-icons/MaterialCommunityIcons';
import { TextInputProps } from 'react-native';

import { ScreenSize, Spacing } from '../../../utils/DesignSystem'

interface InputRef {
  focus(): void;
}

interface InputProps extends TextInputProps {
  name: string;
  icon: string;
  options: Array<SelectorOptions>;
  placeholder?: {label: string};
  rightIcon?: string;
  setIsHidden?: Function;
  isHidden?: boolean;
}

interface SelectorOptions {
  label: string;
  value: string | number | [];
}

interface ContainerProps {
  isFocused: boolean;
  hasError: boolean;
}

const Container = styled.View<ContainerProps>`
  width: ${ScreenSize.width * 0.8}
  height: ${Spacing.xlarge};
  padding: 0 16px;

  margin-bottom: ${Spacing.small};
  border-bottom-color: #f0e4e4;
  border-bottom-width: 1px;

  align-items: center;
  justify-content: center;
  flex-direction: row;

  ${(props) =>
    props.isFocused &&
    css`
      border-bottom-color: green;
    `}

    ${(props) =>
    props.hasError &&
    css`
      border-bottom-color: red;
    `}
`;

const Icon = styled(MCIcon)`
  margin-right: 16px;
`;

const SelectorNative: React.RefForwardingComponent<InputRef, InputProps> = (
  { name, icon, options, placeholder, isHidden, setIsHidden, rightIcon, ...rest },
  ref,
) => {
  const pickerRef = useRef(null);
  const [option, setOption] = useState("");
  const { registerField, defaultValue = '', fieldName, error } = useField(name);
  const [isFocused, setIsFocused] = useState(false);
  const [isFilled, setIsFilled] = useState(false);

  useEffect(() => {
    registerField({
      name: fieldName,
      ref: pickerRef.current,
      path: "props.value",
      clearValue(ref) {
        ref.props.onValueChange(ref.props.placeholder.value);
      },
      getValue(ref) {
        return ref.props.value;
      },
    });
  }, [fieldName, registerField]);

  return (
    <Container isFocused={isFocused} hasError={!!error}>
      <Icon
        name={icon}
        size={18}
        color={isFocused || isFilled ? 'green' : '#FFFFFF90'}
      />
        <RNPickerSelect
          {...rest}
          ref={pickerRef}
          placeholder={placeholder}
          value={option}
          doneText="Select"
          onValueChange={setOption}
          useNativeAndroidPickerStyle={false} //only android
          style={{
            ...pickerSelectStyles,
          }}
          items={options}
          Icon={() => {
            return <MCIcon name="arrow-down" size={24} color={isFocused || isFilled ? 'green' : '#FFFFFF90'} />;
          }}
        />
      </Container>
  );
}

const pickerSelectStyles = StyleSheet.create({
  placeholder: {
    color: "#FFF",
  },
  inputIOS: {
    backgroundColor: "transparent",
    width: ScreenSize.width * 0.62,
    alignSelf: 'flex-start',
    height: Spacing.xlarge,
    paddingTop: Spacing.none,
    color: "#f0e4e4",


  },
  inputAndroid: {
    backgroundColor: "transparent",
    width: ScreenSize.width * 0.62,
    alignSelf: 'center',
    height: Spacing.xlarge,
    paddingTop: Spacing.none,
    color: "#f0e4e4",
  },
  iconContainer: {
    top: Platform.OS == "ios" ? 15 : 21,
  },
});

export default forwardRef(SelectorNative);
```

Then I call this component passing the props I want

```
 <SelectorNative
     ref={citzenshipRef}
    name="nationality"
    options={countries} // an array like ({label: 'Afghanistan', value: 'Afghanistan'}) 
    icon="earth"
    placeholder={{ label: tl.t('profile.citzenship') }}
    onSubmitEditing={() => { addressRef.current?.focus(); }}
  />
```

**Comment by luanccp** [comment]
> precisely for that reason use another picker library, because you cannot get the picker value

Yes, I think you're right I'll handle it manually. But thanks anyway! Both of you :)
