### ISSUE TITLE
ImageInput not working 

### ISSUE THREAD

**Issue by luizlcezario** [unform/unform#327]
I create a component with the code in the documentation about Input Image and , import then in one of my pages give a prop "name" and , i expect that will show something , but the give me the error( TypeError: Cannot read property 'img' of undefined )
'img' is the prop name that i had give to the compoment. I try to change the types to the same of the Input examples but nothing works ,pleases help me !

**Comment by carlosallexandre** [comment]
@luizlcezario could you share the form and the component for check them?

**Comment by HelioSilva** [comment]
I have a similar problem that ImageInput does not work and I ended up solving it using formdata.

No método onSubmit: 

```
             const config = {
                headers: { "Content-Type": "multipart/form-data" },
              };
              let fd = new FormData();
              fd.append("img", data.img);
              await api.put("/users", fd, config);
```
@luizlcezario try to use like that with formdata.

My problem is that I want to change both information and name and image at once, but it doesn't work, I have to change the separate file information.

**Comment by jpedroschmitz** [comment]
Closing this to lack of information on how to reproduce the error.

I'll be glad to reopen in case anyone provides an example.
