### ISSUE TITLE
Material-ui Switch

### ISSUE THREAD

**Issue by GustavoTayer** [unform/unform#336]
Não consigo obter o valor no switch do material-ui quando passo valor dentro de um 

```javascript
formRef.current.setData(cliente)
```

cliente possui: 
``` json
{ "ativo": true, "nome": "qualquer coisa"}
```
como foi feito o Switch:

``` javascript
import React, { useRef, useEffect } from 'react';

import { Switch as BaseSwitch } from '@material-ui/core';
import { useField } from '@unform/core';

const Switch = ({
  name,
  ...restProps
}) => {
  const inputRef = useRef(null);
  const { fieldName, defaultValue = false, registerField } = useField(name);

  useEffect(() => {
    if (fieldName) {
      registerField({
        name: fieldName,
        ref: inputRef.current,
        path: 'checked',
      });
    }
  }, [fieldName, registerField]);

  return (
    <BaseSwitch
      {...restProps}
      name={name}
      defaultChecked={Boolean(defaultValue)}
      inputRef={inputRef}
    />
  );
};

export default Switch
```

Porém quando eu aperto no botão na tela ele altera o valor do ativo no form, apenas não está conseguindo pegar o valor ao dar o setData. Quando uso initialData no form ele funciona também...

**Comment by carlosallexandre** [comment]
Hey @GustavoTayer, 

You need provide a **setValue** on **registerField** for this use case. Try this:
```js
useEffect(() => {
    if (fieldName) {
      registerField({
        name: fieldName,
        ref: inputRef.current,
        getValue: (ref) => ref.checked,
        setValue: (ref, value) => {
          ref.checked = Boolean(value);
        },
        clearValue: (ref) => {
          ref.checked = false;
        }
      });
    }
  }, [fieldName, registerField]);
```

Let me know if it works to u.

**Comment by jpedroschmitz** [comment]
Hey @GustavoTayer, I am going to close this issue because it is not following the guidelines [described here](https://github.com/unform/unform/blob/master/.github/CONTRIBUTING.md#language).

While contributing or interacting in any way in this project, refrain from using any language other than English.

I recommend you open a new issue in English.
