### ISSUE TITLE
Add a new example to checkbox

### ISSUE THREAD

**Issue by leciric** [unform/unform#344]
**Description of issue**
I was trying to reproduce the example of checkbox, but I realized that there is only one example and it uses the field options.
I'd like to know if is possible to add a new example, using only a checkbox without options and labels.

**Usage example**
Something like this `<Input name="checkbox"  />`
and not like this `<Input name="checkbox" options={someOptionsHere} />`

If I'm not being clear, please let me know if I can do a better explication.

**Comment by carlosallexandre** [comment]
Hey @leciric,

I think i get you. 
I worked on a simple solution ([Check it here](https://codesandbox.io/s/unform-checkbox-338w1?file=/src/App.tsx)). But it needs more test and some adjusts. 

Let's discuss more until we get a great solution. 
I wait your feedback.

**Comment by jpedroschmitz** [comment]
Hey @leciric, we are going to include examples on a dedicated folder on the repository soon.

The checkbox component is already planned and will be added together with other components, like Input, Select...

**Comment by leciric** [comment]
> Hey @leciric,
> 
> I think i get you.
> I worked on a simple solution ([Check it here](https://codesandbox.io/s/unform-checkbox-338w1?file=/src/App.tsx)). But it needs more test and some adjusts.
> 
> Let's discuss more until we get a great solution.
> I wait your feedback.
Just saw your solution, and helped me a lot. Exactly what I was thinking. 
Thank you so much.


> Hey @leciric, we are going to include examples on a dedicated folder on the repository soon.
> 
> The checkbox component is already planned and will be added together with other components, like Input, Select...
That's great, is this plan open to us?

**Comment by jpedroschmitz** [comment]
Yes, for sure @leciric. Probably next week we will be adding the first official examples.

After that, the community can add new examples or improve the existing ones.

**Comment by jpedroschmitz** [comment]
Hey @leciric, I have created [this example](https://codesandbox.io/s/condescending-swirles-eit86?file=/src/components/Checkbox.js) (it's in JavaScript, but it's straightforward to change to TypeScript).

If you need any further help, let me know!
