### ISSUE TITLE
Select Async UNFORM

### ISSUE THREAD

**Issue by lucasdzuc** [unform/unform#346]
I tried to use React Select - Async from UNFORM passing the data that comes from my API, but in the Select fields the value is not filled.  I tried to make some changes, but even the data appearing in the Select fields of the form, after I submit and then check the console.log (data) the Selects values ​​are empty.

**Description of bug**
Selec does not work according to unform api

**To Reproduce**

**Expected behavior**

Select filled with the value that comes from the API and the user can change the option.

**Exception or Error**
<pre><code>
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

Please update the following components: Async, Select
</code></pre>

**Screenshots**
![print-1](https://user-images.githubusercontent.com/45245073/105618153-ec094080-5dc2-11eb-8388-d08f83a2178f.jpg)
![print-2](https://user-images.githubusercontent.com/45245073/105618155-ef9cc780-5dc2-11eb-8034-51052f080225.jpg)
![print-3](https://user-images.githubusercontent.com/45245073/105618156-f1ff2180-5dc2-11eb-89e6-24a72a1a1c05.jpg)
![print-4](https://user-images.githubusercontent.com/45245073/105618158-f4fa1200-5dc2-11eb-91bc-3bfff3dde7ca.jpg)
![print-5](https://user-images.githubusercontent.com/45245073/105618160-f88d9900-5dc2-11eb-94a2-1bcdda992365.jpg)

**Environment:**

 Add information about your environment
 - OS: [Windows] 
 - Browser [Chrome ( 88.0.4324.104)]
 - Node [v12.17.0]

**Additional context**

I'm trying to use the FORM's Select without Typescript on the product update page.

**Comment by carlosallexandre** [comment]
@lucasdzuc look this [codesandbox](https://codesandbox.io/s/unform-issue283-nihb7?file=/src/components/Select.tsx) and tell me if it worked for u. 

If don't i will figure out another solution.

**Comment by lucasdzuc** [comment]
> @lucasdzuc como são recebidos os dados de suas costas?

are received as JSON

**Comment by lucasdzuc** [comment]
![print-6](https://user-images.githubusercontent.com/45245073/105638589-27068500-5e52-11eb-84d3-9cadbf83a7c0.jpg)

**Comment by carlosallexandre** [comment]
@lucasdzuc [try this](https://github.com/unform/unform/issues/125#issuecomment-682320073). Tell me if don't works.

**Comment by lucasdzuc** [comment]
now the value is filled with "undefined"

**Comment by lucasdzuc** [comment]
![print-7](https://user-images.githubusercontent.com/45245073/105646760-74015000-5e80-11eb-9b83-69d7ac9a8df5.jpg)

```js
import React, { useRef, useEffect } from 'react';
import AsyncSelect from "react-select/async";
import { useField } from '@unform/core';

const Select = ({ name, ...rest }) => {

  const selectRef = useRef(null);

  const { fieldName, defaultValue, registerField, error } = useField(name);

  useEffect(() => {
    registerField({
      name: fieldName,
      ref: selectRef.current,
      path: "value",
      getValue: (ref) => ref.state.value,
      setValue: (ref, value) => {
        ref.select.select.setValue(value || null);
      },
      clearValue: (ref) => {
        ref.select.clearValue();
      }
    });
  }, [fieldName, registerField]);
  
  return (
    <div>
      <AsyncSelect
        ref={selectRef}
        defaultValue={defaultValue}
        classNamePrefix="react-select"
        {...rest}
      />
      { error && <span style={{ color: "#f00" }}>{error}</span>}
    </div>
  );
};
export default Select;
```

**Comment by carlosallexandre** [comment]
replace on your **setValue** to
```js
setValue: (ref, value) => {
        ref.select.setValue(value || null);
      },
```

**Comment by lucasdzuc** [comment]
"Unhandled Rejection (TypeError): ref.select.setValue is not a function
setValue"

![image](https://user-images.githubusercontent.com/45245073/105646909-5bde0080-5e81-11eb-907b-74722087262e.png)

**Comment by lucasdzuc** [comment]
any suggestions for this problem? @diego3g

**Comment by carlosallexandre** [comment]
For **Async Select** use like below:
```js
useEffect(() => {
    registerField({
      name: fieldName,
      ref: selectRef.current,
      getValue: (ref) => ref.select.state.value,
      setValue: (ref, value) => {
        ref.select.select.setValue(value || null);
      },
      clearValue: (ref) => {
        ref.select.select.clearValue();
      }
    });
  }, [fieldName, registerField]);
```

[Codesandbox](https://codesandbox.io/s/unform-react-select-async-ggv1q?file=/src/components/Select.tsx:372-724)

**Comment by lucasdzuc** [comment]
Can't do it without Typescript?

**Comment by carlosallexandre** [comment]
Just use the registerField like shown above...
Without any problem...

**Comment by lucasdzuc** [comment]
error in filling the select

![image](https://user-images.githubusercontent.com/45245073/105648854-723d8980-5e8c-11eb-8fde-45c0cbe0dbbf.png)

**Comment by lucasdzuc** [comment]
the values are coming as an object

![image](https://user-images.githubusercontent.com/45245073/105649203-fc3a2200-5e8d-11eb-8b45-450e0331ace8.png)

**Comment by carlosallexandre** [comment]
Sure...
Parse them the way u want on **getValue** provide at **registerField**

**Comment by lucasdzuc** [comment]
Ok, I'm testing here, when they are loaded, they load correctly, but when I change options they load as an object

**Comment by carlosallexandre** [comment]
Remove **options** and let just **defaultOptions**

**Comment by lucasdzuc** [comment]
I managed to solve

**Comment by lucasdzuc** [comment]
Solution: added another "value" on getValue at the end.

```js
useEffect(() => {
    registerField({
      name: fieldName,
      ref: selectRef.current,
      path: "value",
      getValue: (ref) => ref.select.state.value.value,
      setValue: (ref, value) => {
        ref.select.select.setValue(value);
      },
    });
  }, [fieldName, registerField]);
```

**Comment by lucasdzuc** [comment]
Thanks a lot for the help @carlosallexandre

**Comment by lucasdzuc** [comment]
If you happen to know what that warning means, let me know?

![image](https://user-images.githubusercontent.com/45245073/105650249-f0e8f580-5e91-11eb-9796-668969caf278.png)
